language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "Pre-testing install - nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "No tests"

script:
  # These build will happen in the Travis worker node
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed elijahkarori/udagram-api-feed
  - docker tag udagram-api-user elijahkarori/udagram-api-user
  - docker tag reverseproxy elijahkarori/reverseproxy
  - docker tag udagram-frontend elijahkarori/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elijahkarori/udagram-api-feed
  - docker push elijahkarori/udagram-api-user
  - docker push elijahkarori/reverseproxy
  - docker push elijahkarori/udagram-frontend

